### ISSUE TITLE
show as ipad style?

### ISSUE THREAD

**Issue by tomeraz** [onlyhom/mobileSelect.js#30]
is it possible to show the picker like in ipad (in place) and not on the bottom of the window?

![image](https://user-images.githubusercontent.com/7067145/33735372-c4f13fda-db97-11e7-9df3-3fda8bfa3fa8.png)

**Comment by onlyhom** [comment]
Of course, you can add @media at the end of mobileSelect.css. Here's my change, which can be used as a reference:
``` css
@media screen and (min-width: 768px) {
  .mobileSelect .content {
    width: 60%;
    left: 20%;
    bottom: 50%;
    border-radius: 10px;
    -moz-transform: scale(0.4);
    -o-transform: scale(0.4);
    -webkit-transform: scale(0.4);
    transform: scale(0.4);
  }
  .mobileSelect-show .content {
    -moz-transform: scale(1);
    -o-transform: scale(1);
    -webkit-transform: scale(1);
    transform: scale(1);
  }
}
```
